import { QuestType } from "./useStore";

export interface QuestData {
  id: string;
  title: string;
  description: string;
  difficulty: "하" | "중" | "상";
  rewardXP: number;
  isCompleted: boolean;
  type: QuestType;
  targetStat?: string;
  statIncrease?: number;
}

export const ALL_QUESTS: QuestData[] = [
  {
    "id": "D001",
    "title": "1km 달리기",
    "description": "기상 후 가볍게 1km 뛰며 하루를 연다",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D002",
    "title": "2km 달리기",
    "description": "2km 러닝으로 심폐지구력 다지기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D006",
    "title": "팔굽혀펴기 30개",
    "description": "정자세로 팔굽혀펴기 30개",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 1
  },
  {
    "id": "D009",
    "title": "윗몸일으키기 30개",
    "description": "복근 운동 윗몸일으키기 30개",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 1
  },
  {
    "id": "D015",
    "title": "플랭크 1분",
    "description": "코어 플랭크 1분 버티기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 1
  },
  {
    "id": "D017",
    "title": "스쿼트 50개",
    "description": "하체 스쿼트 50개",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 1
  },
  {
    "id": "D019",
    "title": "줄넘기 300개",
    "description": "줄넘기 300개 완수",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D022",
    "title": "계단 오르기 10층",
    "description": "생활관 계단 10층 오르기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D024",
    "title": "스트레칭 10분",
    "description": "취침 전 전신 스트레칭 10분",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D025",
    "title": "아침 구보 참여",
    "description": "아침 구보에 적극 참여",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D026",
    "title": "런지 50개",
    "description": "런지 50개로 하체 단련",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 1
  },
  {
    "id": "D029",
    "title": "책 10페이지 읽기",
    "description": "독서 10페이지로 마음의 양식",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D033",
    "title": "영단어 10개 암기",
    "description": "영어 단어 10개 외우기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D037",
    "title": "한국사 1강 듣기",
    "description": "한국사 인강 1강 수강",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D039",
    "title": "대학교·군대 E러닝 1개 듣기",
    "description": "대학 학점·군 e러닝 강좌 1개 수강",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D042",
    "title": "신문 사설 1편 읽기",
    "description": "신문 사설 정독으로 사고력 향상",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D043",
    "title": "시사 뉴스 3개 읽기",
    "description": "오늘의 시사 뉴스 3건 정리",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D044",
    "title": "일기 쓰기",
    "description": "하루를 돌아보는 일기 작성",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D046",
    "title": "한자 10개 암기",
    "description": "한자 10개 외우기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D047",
    "title": "영어 회화 표현 5개 암기",
    "description": "실전 영어 표현 5개 암기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D050",
    "title": "손글씨 연습 1페이지",
    "description": "또박또박 손글씨 1페이지",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 1
  },
  {
    "id": "D053",
    "title": "부대원 칭찬 1회",
    "description": "동료의 장점을 찾아 칭찬",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D054",
    "title": "부대원 칭찬 2회",
    "description": "부대원 2명에게 칭찬 전하기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D056",
    "title": "솔선수범 1회",
    "description": "궂은일에 먼저 나서기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D059",
    "title": "후임 챙기기 1회",
    "description": "후임의 적응을 살뜰히 돕기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D060",
    "title": "선임 도와드리기 1회",
    "description": "선임의 업무를 자발적으로 돕기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D061",
    "title": "감사 인사 전하기",
    "description": "도움받은 일에 감사 표현",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D062",
    "title": "먼저 인사하기",
    "description": "마주치는 전우에게 먼저 인사",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D063",
    "title": "양보하기 1회",
    "description": "사소한 일에 기꺼이 양보",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D064",
    "title": "동기 격려하기",
    "description": "힘든 동기에게 격려 한마디",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D065",
    "title": "고민 들어주기",
    "description": "전우의 고민 진심으로 경청",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D066",
    "title": "분리수거 솔선",
    "description": "분리수거에 먼저 나서기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D067",
    "title": "식판 정리 도움",
    "description": "식사 후 정리를 자발적으로 돕기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D068",
    "title": "공용 공간 청소 자원",
    "description": "공용 공간 청소에 자원",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D070",
    "title": "칭찬 릴레이 참여",
    "description": "칭찬 릴레이에 적극 참여",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D071",
    "title": "병기본 정신전력 학습",
    "description": "정신전력 기본 교육 학습",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D072",
    "title": "군가 1곡 완창",
    "description": "군가 한 곡 가사까지 완벽 숙지",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D073",
    "title": "제식동작 연습",
    "description": "제식동작 정확도 가다듬기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D075",
    "title": "관물대 정리정돈",
    "description": "각 잡힌 관물대 정리",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D076",
    "title": "전투화 손질",
    "description": "전투화 광 내고 손질",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D077",
    "title": "복장 점검",
    "description": "복장·용모 단정 점검",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D078",
    "title": "경례 자세 연습",
    "description": "절도 있는 경례 자세 연습",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D079",
    "title": "암구호 숙지",
    "description": "당일 암구호 정확히 숙지",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D087",
    "title": "물 2리터 마시기",
    "description": "하루 수분 2리터 섭취",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D088",
    "title": "정해진 시간에 취침",
    "description": "규칙적 수면으로 컨디션 관리",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D090",
    "title": "군것질 안 하기",
    "description": "불필요한 간식 절제",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D091",
    "title": "양치 3회",
    "description": "식후 양치 3회 실천",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D092",
    "title": "아침 기상 정시",
    "description": "기상 시간 정확히 지키기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D093",
    "title": "카페인 줄이기",
    "description": "과도한 카페인 절제",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D094",
    "title": "비타민 챙겨먹기",
    "description": "건강 보조 비타민 섭취",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D095",
    "title": "자세 교정 의식",
    "description": "바른 자세 의식적으로 유지",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D096",
    "title": "눈 휴식 스트레칭",
    "description": "눈 피로 풀기 휴식",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 1
  },
  {
    "id": "D097",
    "title": "명상 10분",
    "description": "마음 다스리는 명상 10분",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D098",
    "title": "감사한 일 3가지 적기",
    "description": "오늘 감사한 일 3가지 기록",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D099",
    "title": "가족에게 전화/편지",
    "description": "가족에게 안부 전하기",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D100",
    "title": "긍정 확언 외우기",
    "description": "스스로에게 긍정 확언",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D101",
    "title": "오늘의 목표 세우기",
    "description": "하루 목표 구체적으로 설정",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D102",
    "title": "하루 회고 작성",
    "description": "하루를 돌아보는 회고 정리",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D103",
    "title": "깊은 호흡 5분",
    "description": "심호흡으로 스트레스 완화",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D104",
    "title": "스트레스 일지 작성",
    "description": "스트레스 원인 기록·관리",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 1
  },
  {
    "id": "D003",
    "title": "3km 달리기",
    "description": "체력검정 거리 3km 완주",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D004",
    "title": "4km 달리기",
    "description": "4km 러닝으로 한계 끌어올리기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 2
  },
  {
    "id": "D007",
    "title": "팔굽혀펴기 50개",
    "description": "팔굽혀펴기 50개 달성",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D010",
    "title": "윗몸일으키기 50개",
    "description": "윗몸일으키기 50개 달성",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D012",
    "title": "턱걸이 5개",
    "description": "정자세 턱걸이 5개",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D018",
    "title": "스쿼트 100개",
    "description": "스쿼트 100개 달성",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D020",
    "title": "줄넘기 500개",
    "description": "줄넘기 500개 완수",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 2
  },
  {
    "id": "D021",
    "title": "버피 30개",
    "description": "전신 버피 30개",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D023",
    "title": "맨몸운동 1세트",
    "description": "맨몸 서킷 운동 1세트 완수",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D027",
    "title": "덤벨 운동 20분",
    "description": "체력단련실 덤벨 운동 20분",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D028",
    "title": "복근 운동 세트",
    "description": "복근 루틴 1세트 완수",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 2
  },
  {
    "id": "D030",
    "title": "책 20페이지 읽기",
    "description": "독서 20페이지 완독",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D031",
    "title": "책 30페이지 읽기",
    "description": "독서 30페이지 완독",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D034",
    "title": "영단어 20개 암기",
    "description": "영어 단어 20개 외우기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D035",
    "title": "영단어 30개 암기",
    "description": "영어 단어 30개 외우기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D038",
    "title": "자격증 인강 1강 듣기",
    "description": "자격증 인강 1강 수강",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D040",
    "title": "대학교·군대 E러닝 2개 듣기",
    "description": "대학 학점·군 e러닝 강좌 2개 수강",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D041",
    "title": "자격증 문제 20개 풀기",
    "description": "자격증 기출 20문제 풀이",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D045",
    "title": "독서 감상 노트 작성",
    "description": "읽은 내용 감상 노트 정리",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D048",
    "title": "코딩 1문제 풀기",
    "description": "알고리즘 1문제 해결",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D049",
    "title": "토익 단어 30개 암기",
    "description": "토익 빈출 단어 30개 암기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D052",
    "title": "전공 서적 5페이지 정리",
    "description": "전공 서적 5페이지 요약 정리",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "D055",
    "title": "부대원 칭찬 3회",
    "description": "부대원 3명에게 칭찬 전하기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "D057",
    "title": "솔선수범 2회",
    "description": "솔선수범 2회 실천",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "D069",
    "title": "신병 적응 도움",
    "description": "신병의 부대 적응 돕기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "D074",
    "title": "총기 손질",
    "description": "개인화기 분해·손질·결합",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D080",
    "title": "주특기 복습 30분",
    "description": "주특기 지식 30분 복습",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D081",
    "title": "무전 용어 암기",
    "description": "무전 통신 용어 암기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D082",
    "title": "작전 지도 숙지",
    "description": "작전 지역 지도 숙지",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D083",
    "title": "응급처치 절차 복습",
    "description": "기본 응급처치 절차 복습",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D084",
    "title": "화생방 대응 절차 복습",
    "description": "화생방 상황 대응 절차 복습",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D085",
    "title": "보고 체계 숙지",
    "description": "지휘·보고 체계 숙지",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D086",
    "title": "전투수칙 암기",
    "description": "전투수칙 9개 항 암기",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "D089",
    "title": "금연 하루 성공",
    "description": "오늘 하루 금연 성공",
    "difficulty": "중",
    "rewardXP": 30,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "D005",
    "title": "5km 달리기",
    "description": "5km 장거리 러닝 완주",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "체력",
    "statIncrease": 3
  },
  {
    "id": "D008",
    "title": "팔굽혀펴기 100개",
    "description": "팔굽혀펴기 100개 도전",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 3
  },
  {
    "id": "D011",
    "title": "윗몸일으키기 100개",
    "description": "윗몸일으키기 100개 도전",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 3
  },
  {
    "id": "D013",
    "title": "턱걸이 10개",
    "description": "턱걸이 10개 달성",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 3
  },
  {
    "id": "D014",
    "title": "턱걸이 15개",
    "description": "턱걸이 15개 도전",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 3
  },
  {
    "id": "D016",
    "title": "플랭크 3분",
    "description": "플랭크 3분 버티기",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "근력",
    "statIncrease": 3
  },
  {
    "id": "D032",
    "title": "책 50페이지 읽기",
    "description": "독서 50페이지 정주행",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 3
  },
  {
    "id": "D036",
    "title": "영단어 50개 암기",
    "description": "영어 단어 50개 외우기",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 3
  },
  {
    "id": "D051",
    "title": "모의고사 1과목 풀기",
    "description": "자격증 모의고사 한 과목 풀이",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "지력",
    "statIncrease": 3
  },
  {
    "id": "D058",
    "title": "솔선수범 3회",
    "description": "솔선수범 3회 실천",
    "difficulty": "상",
    "rewardXP": 45,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "정신력",
    "statIncrease": 3
  },
  {
    "id": "D105",
    "title": "출차 전 차량 일일점검",
    "description": "운행 전 차량 상태 일일점검 완료",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D106",
    "title": "배차일지 정확히 기록",
    "description": "운행 내역 배차일지 정확히 기록",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D107",
    "title": "운행 후 차량 청소·정비",
    "description": "운행 종료 후 차량 청소·기본 정비",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D108",
    "title": "운행 전 안전 브리핑 숙지",
    "description": "출발 전 안전 운행 수칙 숙지",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D109",
    "title": "응급처치 술기 1종 복습",
    "description": "지혈·CPR 등 응급처치 술기 복습",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D110",
    "title": "의무물자 재고 점검",
    "description": "의무실 약품·물자 재고 점검",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D111",
    "title": "구급낭·키트 점검",
    "description": "출동 대비 구급낭 점검",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D112",
    "title": "부대원 건강상태 확인 지원",
    "description": "환자 발생 여부 확인 지원",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D113",
    "title": "무전기 상태 점검",
    "description": "개인·공용 무전기 상태 점검",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D114",
    "title": "통신 보안 수칙 숙지",
    "description": "당일 통신 보안 수칙 숙지",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D115",
    "title": "안테나·배터리 점검",
    "description": "통신장비 안테나·배터리 점검",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "D116",
    "title": "호출부호·주파수 숙지",
    "description": "당일 호출부호·주파수 숙지",
    "difficulty": "하",
    "rewardXP": 15,
    "isCompleted": false,
    "type": "daily",
    "targetStat": "생존력",
    "statIncrease": 1
  },
  {
    "id": "W004",
    "title": "정신전력 병기본",
    "description": "정신전력 기본훈련 이수",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 2
  },
  {
    "id": "W042",
    "title": "주간 일기 7일 작성",
    "description": "한 주 매일 일기 작성",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "W057",
    "title": "근무 일지 작성 완수",
    "description": "한 주 근무 일지 성실 작성",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "W074",
    "title": "주간 청소 평가 우수",
    "description": "생활관 청소 평가 우수",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "W075",
    "title": "생활관 정리 우수",
    "description": "생활관 정리정돈 우수 평가",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "W088",
    "title": "사이버지식정보방 자기계발 5회",
    "description": "사지방에서 자기계발 학습 5회",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 2
  },
  {
    "id": "W092",
    "title": "군종 활동 참여",
    "description": "군 종교활동 참여로 마음 다지기",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "W094",
    "title": "군적금 납입 목표 달성",
    "description": "장병내일준비적금 납입 목표 달성",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "W100",
    "title": "주간 감사일기 7일",
    "description": "한 주 매일 감사일기 작성",
    "difficulty": "하",
    "rewardXP": 60,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 2
  },
  {
    "id": "W001",
    "title": "핵 및 화생방 병기본",
    "description": "핵·화생방 방호 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W002",
    "title": "전투부상자처치 병기본",
    "description": "전투부상자 처치 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W003",
    "title": "주특기 병기본",
    "description": "주특기 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W005",
    "title": "경계 병기본",
    "description": "경계 작전 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W007",
    "title": "구급법 병기본",
    "description": "응급 구급법 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W010",
    "title": "화기 분해결합 병기본",
    "description": "개인화기 분해결합 숙달 평가",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W011",
    "title": "통신 병기본",
    "description": "야전 통신 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W013",
    "title": "진지공사 병기본",
    "description": "진지 구축 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W014",
    "title": "위장술 병기본",
    "description": "위장·은폐 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W016",
    "title": "정찰 병기본",
    "description": "정찰 임무 기본훈련 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W020",
    "title": "주간 달리기 20km 달성",
    "description": "한 주 누적 20km 러닝 완수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 4
  },
  {
    "id": "W025",
    "title": "주간 운동 5회 출석",
    "description": "한 주 운동 5회 실천",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 4
  },
  {
    "id": "W028",
    "title": "체력검정 팔굽혀펴기 목표 달성",
    "description": "측정 팔굽혀펴기 목표치 달성",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W029",
    "title": "체력검정 윗몸일으키기 목표 달성",
    "description": "측정 윗몸일으키기 목표치 달성",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W030",
    "title": "주간 플랭크 누적 30분",
    "description": "한 주 누적 플랭크 30분",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "근력",
    "statIncrease": 4
  },
  {
    "id": "W031",
    "title": "주간 줄넘기 3000개",
    "description": "한 주 누적 줄넘기 3000개",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 4
  },
  {
    "id": "W032",
    "title": "체력단련실 5회 이용",
    "description": "한 주 체력단련실 5회 이용",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 4
  },
  {
    "id": "W033",
    "title": "주간 코어 운동 완수",
    "description": "한 주 코어 루틴 꾸준히 완수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "근력",
    "statIncrease": 4
  },
  {
    "id": "W034",
    "title": "주간 독서 1권 완독",
    "description": "한 주에 책 1권 완독",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W035",
    "title": "주간 영단어 100개 암기",
    "description": "한 주 영단어 100개 암기",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W037",
    "title": "자격증 모의고사 1회 응시",
    "description": "자격증 모의고사 풀이·채점",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W038",
    "title": "한국사 5강 수강",
    "description": "한국사 인강 5강 수강",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W039",
    "title": "자격증 인강 5강 수강",
    "description": "자격증 인강 5강 수강",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W041",
    "title": "토익 모의고사 1회",
    "description": "토익 모의고사 1회 응시",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W043",
    "title": "주간 시사 정리 노트 작성",
    "description": "한 주 시사 이슈 정리 노트",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W044",
    "title": "전공 서적 1챕터 정리",
    "description": "전공 서적 한 챕터 요약",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W046",
    "title": "어학 스터디 참여",
    "description": "부대 어학 스터디 참여",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W047",
    "title": "독후감 1편 작성",
    "description": "읽은 책으로 독후감 작성",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W049",
    "title": "주특기 교육 이수",
    "description": "주특기 보수 교육 이수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W050",
    "title": "장비 정비 완료",
    "description": "담당 장비 주간 정비 완료",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W051",
    "title": "차량 점검 완료",
    "description": "담당 차량 정기 점검 완료",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W052",
    "title": "통신장비 점검",
    "description": "통신장비 상태 점검·관리",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W053",
    "title": "화기 정비 완료",
    "description": "공용·개인 화기 정비 완료",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W054",
    "title": "보급 물자 정리",
    "description": "보급 물자 재고 정리·관리",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W056",
    "title": "상황 보고서 작성",
    "description": "주간 상황 보고서 작성",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W059",
    "title": "신규 장비 숙지",
    "description": "신규 도입 장비 운용 숙지",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W060",
    "title": "사격 훈련 참여",
    "description": "정기 사격 훈련 참여",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W076",
    "title": "주간 부대원 칭찬 10회",
    "description": "한 주 부대원 칭찬 10회",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W077",
    "title": "주간 솔선수범 7회",
    "description": "한 주 솔선수범 7회 실천",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W080",
    "title": "주간 봉사활동 참여",
    "description": "부대·대민 봉사활동 참여",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W081",
    "title": "헌혈 참여",
    "description": "단체 헌혈에 참여",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W082",
    "title": "부대 행사 자원봉사",
    "description": "부대 행사 운영 자원봉사",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W084",
    "title": "생활관 분위기 개선 활동",
    "description": "생활관 화합 분위기 조성",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W086",
    "title": "군 e러닝 1과정 수료",
    "description": "나라배움터 등 군 e러닝 1과정 수료",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W087",
    "title": "대학 원격강좌 1주차 수강",
    "description": "학점은행·원격대학 1주 분량 수강",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W089",
    "title": "영어회화 스터디 5회 참여",
    "description": "부대 영어회화 스터디 5회 참여",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W090",
    "title": "자격증 실기 연습 주간 완수",
    "description": "자격증 실기 연습 한 주 완수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W091",
    "title": "독서토론회 참여",
    "description": "부대 독서토론회 참여",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 4
  },
  {
    "id": "W093",
    "title": "위문편지 답장 5통 작성",
    "description": "받은 위문편지에 답장 5통 작성",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W096",
    "title": "주간 영점사격 완료",
    "description": "개인화기 영점사격 완료",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W097",
    "title": "주간 금연 7일 성공",
    "description": "한 주 금연 7일 성공",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W098",
    "title": "주간 절주 성공",
    "description": "한 주 음주 절제 성공",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W099",
    "title": "주간 규칙적 수면 달성",
    "description": "한 주 규칙적 수면 패턴 유지",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 4
  },
  {
    "id": "W101",
    "title": "주간 명상 5회",
    "description": "한 주 명상 5회 실천",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W102",
    "title": "주간 식단 관리 성공",
    "description": "한 주 건강 식단 관리 성공",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 4
  },
  {
    "id": "W006",
    "title": "각개전투 병기본",
    "description": "각개전투 기본훈련 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W008",
    "title": "수류탄 투척 병기본",
    "description": "수류탄 투척 기본훈련 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W009",
    "title": "사격술 예비훈련 병기본",
    "description": "사격술 예비훈련(PRI) 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W012",
    "title": "분대전술 병기본",
    "description": "분대 단위 전술 기본훈련 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W015",
    "title": "매복 병기본",
    "description": "매복 작전 기본훈련 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W017",
    "title": "야간투시 병기본",
    "description": "야간 투시·관측 훈련 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W018",
    "title": "응급처치 심화 병기본",
    "description": "응급처치 심화 과정 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W019",
    "title": "지뢰 식별 병기본",
    "description": "지뢰·부비트랩 식별 훈련 이수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W021",
    "title": "주간 달리기 30km 달성",
    "description": "한 주 누적 30km 러닝 완수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 6
  },
  {
    "id": "W022",
    "title": "주간 팔굽혀펴기 1000개",
    "description": "한 주 누적 팔굽혀펴기 1000개",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "근력",
    "statIncrease": 6
  },
  {
    "id": "W023",
    "title": "주간 윗몸일으키기 1000개",
    "description": "한 주 누적 윗몸일으키기 1000개",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "근력",
    "statIncrease": 6
  },
  {
    "id": "W024",
    "title": "주간 턱걸이 200개",
    "description": "한 주 누적 턱걸이 200개",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "근력",
    "statIncrease": 6
  },
  {
    "id": "W026",
    "title": "주간 운동 7회 출석",
    "description": "한 주 매일 운동 실천",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "체력",
    "statIncrease": 6
  },
  {
    "id": "W027",
    "title": "체력검정 3km 기록 단축",
    "description": "3km 측정 기록 단축 달성",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 6
  },
  {
    "id": "W036",
    "title": "주간 영단어 200개 암기",
    "description": "한 주 영단어 200개 암기",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 6
  },
  {
    "id": "W040",
    "title": "주간 자격증 문제 100개 풀이",
    "description": "한 주 기출 100문제 풀이",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 6
  },
  {
    "id": "W045",
    "title": "주간 코딩 5문제 풀이",
    "description": "한 주 알고리즘 5문제 풀이",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 6
  },
  {
    "id": "W048",
    "title": "주특기 숙달 평가 통과",
    "description": "주특기 숙달 평가 합격",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W055",
    "title": "작전 브리핑 준비",
    "description": "작전 브리핑 자료 준비",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W058",
    "title": "주특기 멘토링 진행",
    "description": "후임 대상 주특기 멘토링",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W061",
    "title": "야간 사격 훈련",
    "description": "야간 사격 훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W062",
    "title": "전술 훈련 참여",
    "description": "부대 전술 훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W063",
    "title": "행군 10km 완주",
    "description": "완전군장 행군 10km 완주",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W064",
    "title": "행군 20km 완주",
    "description": "완전군장 행군 20km 완주",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W065",
    "title": "유격 훈련 참여",
    "description": "유격 기초 훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W066",
    "title": "혹한기 훈련 참여",
    "description": "혹한기 야외 훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W067",
    "title": "동계 훈련 참여",
    "description": "동계 종합 훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W068",
    "title": "화생방 훈련 참여",
    "description": "화생방 실습 훈련 참여(가스실)",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W069",
    "title": "종합 전술훈련 참여",
    "description": "대대급 종합 전술훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W070",
    "title": "분대 전투 훈련",
    "description": "분대 단위 전투 훈련 완수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W071",
    "title": "진지 구축 훈련",
    "description": "야전 진지 구축 훈련 완수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W072",
    "title": "매복 훈련 참여",
    "description": "야간 매복 훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W073",
    "title": "도하 훈련 참여",
    "description": "하천 도하 훈련 참여",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W078",
    "title": "후임 멘토링 1주",
    "description": "한 주 후임 멘토링 지속",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 6
  },
  {
    "id": "W079",
    "title": "동기 스터디 리드",
    "description": "동기 스터디 운영·리드",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 6
  },
  {
    "id": "W083",
    "title": "갈등 중재 1회",
    "description": "전우 간 갈등 원만히 중재",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 6
  },
  {
    "id": "W085",
    "title": "신병 1주 적응 도우미",
    "description": "신병의 첫 주 적응 도우미",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 6
  },
  {
    "id": "W095",
    "title": "체력검정 대비 프로그램 완수",
    "description": "한 주 체력검정 대비 루틴 완수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "지력",
    "statIncrease": 6
  },
  {
    "id": "W103",
    "title": "주간 목표 100% 달성",
    "description": "그 주 세운 목표 전부 달성",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 6
  },
  {
    "id": "W104",
    "title": "주간 안전 주행 200km 달성",
    "description": "한 주 무사고 200km 주행",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W106",
    "title": "주간 무사고 운행 달성",
    "description": "한 주 무사고 운행 완수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W107",
    "title": "차량 정기점검 완료",
    "description": "담당 차량 주간 정기점검 완료",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W105",
    "title": "주간 안전 주행 500km 달성",
    "description": "한 주 무사고 500km 주행",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W108",
    "title": "야간 운행 안전 완수",
    "description": "야간 운행 임무 안전 완수",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W111",
    "title": "의무실 위생 관리 완수",
    "description": "의무실 청결·위생 관리 완수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W113",
    "title": "의무 보급품 정리·관리",
    "description": "의무 보급품 주간 정리·점검",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "정신력",
    "statIncrease": 4
  },
  {
    "id": "W109",
    "title": "CPR·AED 숙달 평가",
    "description": "심폐소생·자동제세동기 숙달 평가",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W110",
    "title": "부대원 응급처치 교육 실시",
    "description": "부대원 대상 응급처치 교육 진행",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W112",
    "title": "외상처치 시뮬레이션 훈련",
    "description": "모의 외상환자 처치 훈련",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W115",
    "title": "유·무선 통신 점검 완수",
    "description": "유선·무선 통신 상태 점검 완수",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W116",
    "title": "통신 보안 점검 통과",
    "description": "통신 보안 점검 통과",
    "difficulty": "중",
    "rewardXP": 80,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 4
  },
  {
    "id": "W114",
    "title": "야전 통신망 구축 훈련",
    "description": "야전 통신망 설치·운용 훈련",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W117",
    "title": "암호장비 운용 숙달",
    "description": "암호장비 운용 절차 숙달",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  },
  {
    "id": "W118",
    "title": "통신 장애 대응 훈련",
    "description": "통신 장애 상황 대응 훈련",
    "difficulty": "상",
    "rewardXP": 120,
    "isCompleted": false,
    "type": "weekly",
    "targetStat": "생존력",
    "statIncrease": 6
  }
];
